In [13]:
import os
import re
import pandas as pd
import numpy as np
import seaborn as sns

In [50]:
def find_empty_line_no(f):
    lno = 0
    with open(f, "r") as fid:
        for line in fid:
            if len(line) < 2:
                return lno
            lno += 1

def read_grade_file(f):
    data = {}
    with open(f, "r") as fid:
        for line in fid:
            if line.startswith("#"):
                continue
            if len(line) < 2:
                continue
            name, values = line.split(maxsplit=1)
            values_split = values.split()
            try:
                float(values_split[0])
                row = np.fromstring(values, sep=" ")
            except ValueError:
                row = values_split
            data[name] = row
    return pd.DataFrame(data)

In [2]:
grade_dir = r"C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV"

In [52]:
i = 0
all_df = []
for root, dirs, files in os.walk(grade_dir):
    for file in files:
        if file.endswith(".dat"):
            file_path = os.path.join(root, file)
            seed_no = int(re.search(r"seed(\d+)", file_path).group(1))
            cm_no = int(re.search(r"GradeCM(\d+)", file_path).group(1))
            empty_line_no = 3#find_empty_line_no(file_path)
            #df = pd.read_csv(file_path, skiprows=empty_line_no, header=None, sep=r'\s+', index_col=0, engine='c').T
            print(f"Reading {file_path} ...")
            df = read_grade_file(file_path)
            if min(df.shape) == 1:
                print(f"Skipping {file_path} due to insufficient data.")
                continue
            df["seed_no"] = seed_no
            df["cm_no"] = cm_no
            df["file_no"] = i
            
            all_df.append(df) 
            # Perform analysis on the DataFrame 'df'
            i+=1

Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM1.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM10.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM11.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM11.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM12.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM12.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM13.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM13.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM14.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM14.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM15.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM15.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM16.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM16.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM2.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM3.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM4.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM5.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM6.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM7.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM8.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed01\GradeCM9.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM1.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM10.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM11.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM11.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM12.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM12.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM13.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM13.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM14.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM14.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM15.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM15.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM16.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM16.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM2.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM3.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM4.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM5.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM6.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM7.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM8.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed02\GradeCM9.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM1.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM10.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM11.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM11.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM12.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM12.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM13.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM13.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM14.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM14.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM15.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM15.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM16.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM16.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM2.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM3.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM4.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM5.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM6.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM7.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM8.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed03\GradeCM9.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM1.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM10.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM11.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM11.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM12.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM12.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM13.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM13.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM14.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM14.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM15.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM15.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM16.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM16.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM2.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM3.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM4.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM5.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM6.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM7.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM8.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed04\GradeCM9.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM1.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM10.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM11.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM11.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM12.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM12.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM13.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM13.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM14.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM14.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM15.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM15.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM16.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM16.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM2.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM3.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM4.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM5.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM6.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM7.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM8.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed05\GradeCM9.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM1.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM10.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM11.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM11.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM12.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM12.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM13.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM13.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM14.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM14.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM15.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM15.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM16.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM16.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM2.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM3.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM4.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM5.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM6.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM7.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM8.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed06\GradeCM9.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM1.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM10.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM11.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM11.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM12.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM12.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM13.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM13.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM14.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM14.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM15.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM15.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM16.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM16.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM2.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM3.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM4.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM5.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM6.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM7.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM8.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed07\GradeCM9.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM1.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM10.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM11.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM11.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM12.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM12.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM13.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM13.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM14.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM14.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM15.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM15.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM16.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM16.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM2.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM3.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM4.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM5.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM6.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM7.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM8.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed08\GradeCM9.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM1.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM10.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM11.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM11.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM12.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM12.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM13.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM13.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM14.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM14.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM15.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM15.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM16.dat ...
Skipping C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM16.dat due to insufficient data.
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM2.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM3.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM4.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM5.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM6.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM7.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM8.dat ...
Reading C:\Dev\Git\Woodsmith\conf\grade\grade_v4\quarters_17_40_lenCV\seed09\GradeCM9.dat ...

In [53]:
df = pd.concat(all_df, ignore_index=True)

In [54]:
df.describe()

,panel,num_HVs,CM_reloc_h,HV_delay_s,is_crosscut,is_survey,panelCV_m,trunkCV_m,Pol,Hal,Anh,seed_no,cm_no,file_no
count,8.037800e+06,8.037800e+06,8.037800e+06,8.037800e+06,8.037800e+06,8.037800e+06,8.037800e+06,8.037800e+06,8.037800e+06,8.037800e+06,8.037800e+06,8.037800e+06,8.037800e+06,8.037800e+06
mean,4.040240e+01,3.126574e+01,6.870960e-01,8.516333e+01,3.566026e-01,1.904750e-02,5.891512e+02,1.592904e+03,8.432017e+01,1.652952e+00,1.074609e+01,5.050000e+01,5.476349e+00,4.995196e+02
std,1.992756e+01,1.241878e+01,4.863445e+00,2.968945e+01,4.789960e-01,1.366920e-01,5.208459e+02,7.435962e+02,1.014560e+01,2.007519e+00,8.898951e+00,2.886607e+01,2.899778e+00,2.886755e+02
min,1.000000e+00,1.200000e+01,0.000000e+00,1.649300e+01,0.000000e+00,0.000000e+00,0.000000e+00,6.000000e+00,3.250000e+00,0.000000e+00,2.500000e-01,1.000000e+00,1.000000e+00,0.000000e+00
25%,2.300000e+01,2.100000e+01,2.280000e-01,7.069000e+01,0.000000e+00,0.000000e+00,1.430000e+02,1.066000e+03,7.939000e+01,3.200000e-01,4.360000e+00,2.575000e+01,3.000000e+00,2.497500e+02
50%,4.200000e+01,2.600000e+01,3.110000e-01,8.672600e+01,0.000000e+00,0.000000e+00,5.080000e+02,1.367000e+03,8.665000e+01,9.400000e-01,8.010000e+00,5.050000e+01,5.000000e+00,4.995000e+02
75%,5.600000e+01,4.700000e+01,4.400000e-01,1.042820e+02,1.000000e+00,0.000000e+00,9.160000e+02,2.045000e+03,9.176000e+01,2.270000e+00,1.442000e+01,7.525000e+01,8.000000e+00,7.492500e+02
max,7.800000e+01,5.200000e+01,1.680000e+02,1.681300e+02,1.000000e+00,1.000000e+00,2.037000e+03,4.920000e+03,9.857000e+01,3.648000e+01,8.934000e+01,1.000000e+02,1.000000e+01,9.990000e+02

In [55]:
df.groupby("panel")["trunkCV_m"].describe()

          count    mean  std     min     25%     50%     75%     max
panel
1.0     31600.0   657.0  0.0   657.0   657.0   657.0   657.0   657.0
2.0     29600.0   539.0  0.0   539.0   539.0   539.0   539.0   539.0
3.0     15600.0   638.0  0.0   638.0   638.0   638.0   638.0   638.0
4.0     55200.0  1007.0  0.0  1007.0  1007.0  1007.0  1007.0  1007.0
5.0    100400.0   978.0  0.0   978.0   978.0   978.0   978.0   978.0
...         ...     ...  ...     ...     ...     ...     ...     ...
74.0    57600.0  1629.0  0.0  1629.0  1629.0  1629.0  1629.0  1629.0
75.0    68400.0  1366.0  0.0  1366.0  1366.0  1366.0  1366.0  1366.0
76.0    24000.0  1066.0  0.0  1066.0  1066.0  1066.0  1066.0  1066.0
77.0    27600.0  1527.0  0.0  1527.0  1527.0  1527.0  1527.0  1527.0
78.0    22400.0  1259.0  0.0  1259.0  1259.0  1259.0  1259.0  1259.0

[78 rows x 8 columns]

In [57]:
df.groupby("panel")["panelCV_m"].describe()

,count,mean,std,min,25%,50%,75%,max
panel,,,,,,,,
1.0,31600.0,1597.012658,39.247485,1557.0,1557.0,1591.0,1626.0,1660.0
2.0,29600.0,592.716216,42.928232,543.0,543.0,589.0,636.0,664.0
3.0,15600.0,933.000000,0.000000,933.0,933.0,933.0,933.0,933.0
4.0,55200.0,617.576087,66.944326,544.0,544.0,611.0,679.0,723.0
5.0,100400.0,1337.318725,142.714121,1128.0,1197.0,1331.0,1468.0,1569.0
...,...,...,...,...,...,...,...,...
74.0,57600.0,257.062500,107.298397,123.0,167.0,257.0,348.0,438.0
75.0,68400.0,249.742690,110.944943,91.0,147.0,260.0,348.0,435.0
76.0,24000.0,1001.333333,34.880361,963.0,963.0,993.0,1021.0,1050.0
77.0,27600.0,137.608696,40.950771,91.0,91.0,147.0,176.0,204.0
78.0,22400.0,954.482143,21.995613,938.0,938.0,938.0,966.0,997.0